apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-news
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: job
              image: ghcr.io/blackhorseya/blitzcrank:latest
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
